export type TranslationKey =
    | 'cancel'
    | 'confirm'
    | 'save'
    | 'settings.language'

    | 'nav.menu'
    | 'nav.guestWelcome'
    | 'nav.pleaseLogin'
    | 'nav.login'
    | 'nav.logOut'

    | 'sidebar.personas'
    | 'sidebar.underwriter'
    | 'sidebar.businessAnalyst'
    | 'sidebar.home'
    | 'sidebar.dashboard'
    | 'sidebar.manageContent'
    | 'sidebar.contentLibrary'
    | 'sidebar.bulkUpload'
    | 'sidebar.addContent'
    | 'sidebar.viewContent'
    | 'sidebar.addEmployees'
    | 'sidebar.viewEmployees'
    | 'sidebar.manageEmployees'
    | 'sidebar.team'

    | 'footer.hanoverContentManager'
    | 'footer.rightsReserved'
    | 'footer.notice'
    | 'footer.WPI'


    | 'role.lead'
    | 'role.assistantLead'
    | 'role.assistantLeadAndScrumMaster'
    | 'role.fullTime'
    | 'role.ptManager'
    | 'role.ptOwner'
    | 'role.ptAnalyst'

    | 'home.header'
    | 'home.subheader'
    | 'home.mainHeader'
    | 'home.subHeader'
    | 'home.disclaimer'
    | 'home.appBy'
    | 'home.studentProject'
    | 'home.meetTheTeam'
    | 'home.notLoggedIn'
    | 'home.manageFiles'
    | 'home.bubble1'
    | 'home.bubble2'
    | 'home.bubble3'

    | '404';

