"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prismaReadOnly = exports.prisma = void 0;
var adapter_pg_1 = require("@prisma/adapter-pg");
var client_1 = require("../generated/prisma/client");
var connectionString = "".concat(process.env.NEXT_PUBLIC_DATABASE_URL);
var readOnlyConnectionString = "".concat(process.env.DATABASE_URL_READONLY);
var adapter = new adapter_pg_1.PrismaPg({ connectionString: connectionString });
var prisma = new client_1.PrismaClient({ adapter: adapter });
exports.prisma = prisma;
var readOnlyAdapter = new adapter_pg_1.PrismaPg({ connectionString: readOnlyConnectionString });
var prismaReadOnly = new client_1.PrismaClient({ adapter: readOnlyAdapter });
exports.prismaReadOnly = prismaReadOnly;
